version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uxojb7ycxggg"
s3_prefix = "resume"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
